### ISSUE TITLE
Implement fingerprint commands

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [FyraLabs/crosec-rs#1]
I'm currently working on a pam module written in Rust separate from `libfprint`. It currently calls the `ectool` CLI. It would be better to directly use this library instead.

**Comment by ChocolateLoverRaj** [comment]
Related project: https://github.com/ChocolateLoverRaj/cros-fp-pam. @WeirdTreeThing are you interested in contributing?

**Comment by WeirdTreeThing** [comment]
Does that PAM module integrate nicely into desktops (does it say to press your finger to unlock?)

**Comment by ChocolateLoverRaj** [comment]
> Does that PAM module integrate nicely into desktops (does it say to press your finger to unlock?)

I didn't get it to work with the KDE lock screen. I haven't tried it with gnome yet. 

Update: Plasma 6 now properly supports logging in with either password or fingerprint. I am able to unlock the Plasma 6 lock screen with my pam module. The only issue is that the lock screen doesn't run the pam module as root, so somehow the user (in my case `test`) needs to access `cros_fp` without being root. But it should be fine.

Update: GNOME seems to be ignoring `gdm-fingerprint`. Maybe GNOME only uses it if it knows there is a fingerprint enrolled with libfprint. Maybe something like https://github.com/uunicorn/open-fprintd can be used.
